/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.HashMap;
import java.util.Map;

import org.example.core.HttpCommunicationService;
import org.example.core.HttpServerHandler;
import org.example.models.User;

import com.sun.net.httpserver.HttpHandler;

public class App {
    public static void main(String... args) {
        Map<String, HttpHandler> routes = new HashMap<>();
        String apiDomain = "https://api.github.com";

        routes.put("/user", new HttpCommunicationService(User.class, apiDomain + "/users/miniscandal"));

        HttpServerHandler.start(routes);
    }
}
